### ISSUE TITLE
Intégration dans HACS

### ISSUE THREAD

**Issue by jmcollin78** [hekmon/rtetempo#10]
Bonjour,

Super idée cette intégration ! Ca va aider beaucoup de gens.

Par contre, ce serait beaucoup plus simple à installer si elle était disponible automatiquement sous HACS.
Est-ce prévu ?

C'est facile à faire et comme je l'ai déjà fait, je peux aider au besoin

**Comment by hekmon** [comment]
Bonjour @jmcollin78 ,

Merci pour le retour !

Elle est normalement [déjà compatible HACS](https://github.com/hekmon/rtetempo/issues/3#issuecomment-1414315903) le support ayant été rajouté petit à petit lors des dernières mises à jours, même si ce n'est pas encore clairement indiqué dans le readme...

Cela devrait l'être dès la prochaine version qui devrait arriver sous peu ;)

Essayez ce [lien](https://my.home-assistant.io/redirect/hacs_repository/?owner=hekmon&repository=rtetempo&category=integration) en attendant (mais vous devriez pouvoir rajouter le repository manuellement comme l'utilisateur de l'issue #3 l'a fait).

**Comment by hekmon** [comment]
A moins que vous ne parliez d'un ajout [permanent et par default](https://hacs.xyz/docs/publish/include) dans HACS ?

Pour le moment je ne l'avais pas considéré, je pensais simplement rajouter le bouton d'installation rapide dans le readme... Mais pourquoi pas :)

En tout cas tous les prerequis pour HACS sont déjà remplis:
- hacs.json
- info.md
- les actions github de vérifications
- l'icone brand dans home assistant

Yapluka !

**Comment by hekmon** [comment]
Je close suite à la publication de la [v1.3.0](https://github.com/hekmon/rtetempo/releases/tag/v1.3.0) qui ajoute le support officiel de HACS (et le bouton d'installation rapide dans le README).

Si l'issue concernait l'ajout par défaut (et non manuel) n'hésitez pas à l'indiquer.

**Comment by jmcollin78** [comment]
Désolé pour le temps de réponse. Comme le README ne parlait pas d'installation avec HACS, j'ai cru qu'il fallait absolument l'installer manuellement. Du coup RAS.
