### ISSUE TITLE
Saisie ID

### ISSUE THREAD

**Issue by julien23dev** [hekmon/rtetempo#13]
Bonsoir,

Après installation il ne me demande pas de saisir mes identifiants d'API comme indique la doc.

> Une fois l'intégration installée, rendez-vous dans la page des intégrations d'home assistant et recherchez RTE Tempo. L'assistant d'installation vous demandera l'ID Client et l'ID Secret de votre application précédemment créée.

L'intégration est bien présente dans HACS mais quand je clique dessus, il me montre le README...

**Comment by hekmon** [comment]
Que se passe-t-il quand vous cliquez sur le bouton `Télécharger` en bas à droite ? :)

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/3418467/230611077-c86ee3bf-863a-4f75-98ff-19f42efcff69.png">

Vous devriez normalement avoir la modale suivante:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3418467/230611155-ea199504-05af-495a-9a63-74e119522011.png">

Une fois validée, redémarrez votre Home Assistant pour qu'il puisse voir la nouvelle extension installée comme disponible à l'activation.

Après redémarrage, rendez-vous dans l'écran des extensions et cliquez sur `Ajouter une extension`.
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/3418467/230611413-bfcc8538-c5eb-4652-a2cc-2e7b7036b090.png">

Une modale s'ouvre avec toutes les extensions disponibles, cherchez alors `rtetempo`:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/3418467/230611545-77060677-256b-4239-b617-6babffcea321.png">

Sélectionnez l'extension et l'assistant de configuration de `rtetempo` se lance enfin:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/3418467/230611673-bd2b43c4-4061-4290-a191-7e35d86c555b.png">


En effet HACS s'occupe d'installer des extensions extérieurs dans Home Assistant mais ensuite, une fois installée et disponible, comme pour une intégration core vous devez l'activer (et la configurer donc).

**Comment by hekmon** [comment]
En l'absence de retour, je me permets de fermer l'issue.
