### ISSUE TITLE
sensor.edf_tempo_prix_actuel pas mis a jour

### ISSUE THREAD

**Issue by rjullien** [hekmon/rtetempo#14]
Bonsoir,

J'ai installe rtetempo ainsi que les fichiers 2 yaml, les deux sont inclus dans configuration.yaml
La partie tempo fonctionne mais pas le widget avec les prix. 
J'ai du oublier quelque chose mais je ne trouve pas

<img width="435" alt="image" src="https://user-images.githubusercontent.com/22872207/235322550-7b6c89f8-7f6a-4546-b22d-ebba800817f9.png">

Merci

**Comment by hekmon** [comment]
Bonjour,

L'un des 2 templates ne doit pas être inclus. Vous pouvez utiliser les [outils de développeurs](https://my.home-assistant.io/redirect/developer_states/) pour vérifier l'existence des entités. Dans le champ `Filtrer les entités` cherchez:
* `tarif_edf_base` pour valider les [input numbers](https://gist.github.com/hekmon/33cba41728bfe2e4e522851da052f91f)
* `edf_tempo_prix_actuel` pour valider les [templates](https://gist.github.com/hekmon/c2f64f22f58b92eae007797eb1a2732e)

Si je devais deviner, je dirais que vous avez rajouté les includes des gists, mais que les clés étaient déjà présentes dans votre `configuration.yaml`. Donc la seconde qui fait l'include est ignorée. Pour illustrer mon propos:

```yaml
template:
  # configuration deja existante

# ...

template: !include templates.yaml
```

Si tel est le cas vous avez 2 solutions:
* garder la configuration "in file" et y inclure le contenu du fichier `templates.yaml`
* migrer le contenu de la configuration "in file" et la migrer dans le fichier `templates.yaml`

L'idée étant que la clé `template:` n'existe qu'une seule fois dans le fichier de configuration.

**Comment by rjullien** [comment]
Merci, ca fonctionne, je n'ai pas vraiment compris comment

**Comment by pihomeserver** [comment]
Dans mon cas tout était ok, il fallait juste faire une relance de Home Assistant. LE chargement YAML ne semble pas suffire 

Merci bcp pour le boulot réalisé
