### ISSUE TITLE
integration non chargée

### ISSUE THREAD

**Issue by xtro83** [hekmon/rtetempo#15]
bonjour

suite à la mise à niveau du dernier core ( je ne l'avais plus fait depuis 2 mois et ça fonctionnait nickel) , l'integration n'est plus chargée  
quel serait le probleme ?
merci
cordialement 
jc

![rtetempo non chargé](https://user-images.githubusercontent.com/36260342/236619705-a794df2b-7b03-4e84-ba09-f3db4cc9b7a6.jpg)

**Comment by hekmon** [comment]
Tout dépend de comment est installé/mis à jour le core. Après normalement peu importe la méthode, le dossier de configuration (dans lequelle les extensions externes sont) n'est jamais touché.

Difficile d'émettre une théorie avec aussi peu d'infos, commencez par vérifier:

- les logs: que disent-ils à propos de `rtetempo` ?
- est-ce que l'intégration est toujours bien présente dans le dossier `custom_components` ? (peut être que votre mise à jour a effacé d'une manière ou d'une autre le dossier des intégrations extérieurs)

**Comment by hekmon** [comment]
Bonjour @xtro83 ,

Sans retour de votre part je fermerai cette issue.
