### ISSUE TITLE
Jour tempo vs. jour calendaire

### ISSUE THREAD

**Issue by tschiex** [hekmon/rtetempo#17]
Bonjour,

Merci pour cette sympathique et utile intégration. J'ai jeté mon yaml/REST/EDF avec plaisir.

J'observe que le calendrier contient un 

```
message: 🔵
all_day: true
start_time: '2023-08-17 00:00:00'
end_time: '2023-08-18 00:00:00'
location: France
description: Jour Tempo Bleu
attribution: Données fournies par data.rte-france.com
friendly_name: RTE Tempo Calendrier
```

mais un jour Tempo commence à 6:00 et se termine 6:00 le lendemain.

Serait-il possible de faire en sorte de changer systématiquement les start/end times qu'utilise l'extension dans le calendrier?

Le README.md mentionne: 

> un calendrier sur un an (avec la possibilité de passer les évènements en heures réèlles)

mais je ne vois pas comment faire.

**Comment by tschiex** [comment]
Je me réponds après avoir jeté un œil au code:

Dans l'intégration, cliquer sur CONFIGURER et sélectionner le booléen "Ajuster les événements du calendrier à l'heure réelle du changement (6h du matin)"

Désolé pour le dérangement :-)

**Comment by hekmon** [comment]
Ravi que l'intégration vous plaise et que vous ayez trouvé l'option. Je n'étais pas certain que cette option serve à quelqu'un mais par principe je souhaitais qu'elle existe. Ça n'aura donc pas été pour rien 😃
