### ISSUE TITLE
Home Assistant supervisor

### ISSUE THREAD

**Issue by Trebor87** [hekmon/rtetempo#18]
Ceci n'est pas un Issue, c'est juste de l'info en plus

Dans Home Assistant supervisor, IL  n'y a pas de dossier "custom_components"

Sous Debian et Docker le chemin est  usr/share/hassio/homeassistant
Il faut créer un dossier custom_components et copier le dossier rtetempo qui se trouve dans le dossier rtetempo 1.3.xx / custom components une fois de compressé

Dans le web site RTE quand on créer 'une application' il faut choisir Mobile (pas indiqué dans vos instructions)

Bravo pour l'appli, c'est très bien :)

**Comment by hekmon** [comment]
Bonjour,

Je ne suis pas familier avec HA Supervisor mais si ma mémoire est bonne le dossier `custom_components` n'existe pas non plus plus dans la version container.

Pour l'installation, le dossier `custom_components` existe bien dans ce projet et contient le dossier de l'intégration. Il suffit donc de déplacer le dossier `custom_components` de ce projet directement à la racine du dossier de configuration de Home Assistant (pas besoin de le créer à la main).
Le plus simple étant je pense de passer par HACS qui s'occupe normalement de tout cela automatiquement !

Concernant l'application RTE, je ne suis pas certain que le type d'application ait une incidence : la mienne est de type `WEB` par exemple :)

**Comment by romu044** [comment]
Bonjour Hekmon,

Je n'ai pas trouvé rte tempo dans HACS, du coup j'ai téléchargé la release, j'ai décompressé le répertoire rtetempo (j'ai supprimé -1.3.2) dans le répertoire homeassistant/custom_components/ déjà existant.
Après j'ai redémarré HA, mais je n'ai pas RTE Tempo dans la liste des intégrations, du coup je suis un peu perdu
