### ISSUE TITLE
Ha core 2023.8.4

### ISSUE THREAD

**Issue by Crapoto94** [hekmon/rtetempo#19]
After HA update to 2022.8.4,  it does not work (the color).
J'ai fait ma dernière maj HA, et les petits icônes de couleurs ne fonctionne plus. J'ai du faire un rollback de version et revenir à la 2023.8.2

**Comment by hekmon** [comment]
Bonjour,

Je suis moi même sous Home Assistant 2023.8.4 et je ne rencontre pas le problème 🤔 

Que disent les logs de l'intégration ?

À noter aussi qu'hier était un jour de maintenance de l'API de RTE (vous avez du recevoir un mail sur l'adresse utilisée pour créer votre compte/application RTE) : il est possible que cela ait eu un effet de bord chez vous.

**Comment by hekmon** [comment]
Nouvelle version ([v1.3.2](https://github.com/hekmon/rtetempo/releases/tag/v1.3.2)) publié pour Home Assistant 2023.9.X. Avez-vous toujours le problème ?

**Comment by Crapoto94** [comment]
C'est nicke, merci !!!

Le sam. 9 sept. 2023 à 16:25, Edouard Hur ***@***.***> a
écrit :
