### ISSUE TITLE
Fonctionnement des ENUM

### ISSUE THREAD

**Issue by stadros83** [hekmon/rtetempo#21]
Bonjour, tout d'abord merci pour cette fontionnalité !
Désolé de crééer une "issue" pour ça mais je n'ai pas trouvé comment faire autrement.

Je souhaitais savoir s'il y avait un exemple de configuration pour utiliser les "enum" dans Home Assistant ?

Est-ce qu'il faut par exemple créer une condition sur RTE Tempo Couleur actuelle ? Si = Rouge alors ?

Parce que si je regarde les états numériques de home assistant j'ai l'impression qu'il attend plutôt un valeur numérique.

S'il y a un exemple ou un tuto quelque part je suis preneur !

**Comment by hekmon** [comment]
Effectivement ce code YAML n'est pas facile à écrire...

```yaml
platform: state
entity_id:
  - sensor.rte_tempo_prochaine_couleur_visuel
to: 🔴
```

Heureusement qu'il y a les enum ;)
<img width="1046" alt="image" src="https://github.com/hekmon/rtetempo/assets/3418467/9cf5a624-2fa2-49b1-a096-ac92b101cf61">

C'est le déclencheur ou la condition de type `État` :
<img width="242" alt="image" src="https://github.com/hekmon/rtetempo/assets/3418467/d7163ab5-b858-4768-aef8-e097207dced6">


Est-ce que cela répond à votre question ?

**Comment by stadros83** [comment]
Ok merci je n'avais tout simplement pas sélectionné la bonne entité :).
