### ISSUE TITLE
Mise à jour sensors HS depuis le 14/10/2023

### ISSUE THREAD

**Issue by luke7101** [hekmon/rtetempo#22]
Bonjour, les sensors semblent ne pas avoir été mis à jour aujourd'hui. La journée de demain est toujours "unavailable", le "cycle jours restants bleu" à 257 au lieu de 256.
J'étais sous HA 2023.10.2 et je viens de faire la màj 2023.10.3 et de redémarrer donc par la même occasion, ce qui devrait forcer une mise à jour je suppose ?
Je n'ai pas vu de message particulier dans les logs.

**Comment by RedQuarck** [comment]
Ce samedi 14 à 23h00, [le site de RTE](https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/calendrier-des-offres-de-fourniture-de-type-tempo.html) semble ne pas publier non plus la couleur pour dimanche 15:
Le jour du lendemain est vide, et une info bulle laisse entendre qu'il y aurait un problème technique:

![Capture d’écran du 2023-10-14 23-01-47](https://github.com/hekmon/rtetempo/assets/24843224/b6817ca3-a7c3-47a0-94b8-c05c92099b19)

**Comment by stadros83** [comment]
Même soucis de mon côté :) !

**Comment by samourai64** [comment]
idem de mon coté après mise a jour 10.3 et 11 pour l'OS

**Comment by mathieucarbou** [comment]
Bonjour,
Je découvre cette même erreur ce matin:

`2023-10-15 08:48:16.941 WARNING (RTE Tempo API Worker) [custom_components.rtetempo.api_worker] Unexpected delta encountered between today and last result, waiting 0:53:00 as fallback`

Pas de mise à jour des capteurs.

**Comment by hekmon** [comment]
Bonjour à tous,

J'ai bien remarqué le problème hier mais apres une rapide inspection de mes propres logs j'en suis venu à la même conclusion que @RedQuarck : le service de RTE semble rencontrer des difficultés que je ne peux résoudre à leur place.

Concernant les logs que vous voyez un petit peu d'explications :

- par default l'extension récupère 1 an de résultat en tentant d'y include le lendemain (ou plutot au lendemain compris donc jusqu'au sur lendemain)
- Si la couleur du lendemain est publiée, la différence temporelle avec la date du jour courant est de (diff) 2 [cas 1]
- Si la couleur du lendemain n'est pas encore publiée, la différence temporelle est de (diff) 1 [cas 2]
- Seulement nous sommes actuellement dans un cas non normal ou la couleur même du jour n'est pas incluse (diff 0 donc et diff -1 demain) le code passe donc dans une gestion d'erreur/exception (d'ou le warning `unexpected delta`) que j'avais rajouté au cas où avec un temps d'attente correspondant (plus ou moins 1h) avant de réessayer [cas 3].

Pour le moment donc pas grand chose à faire si ce n'est attendre que RTE règle le problème de son côté et s'assurer que l'intégration reprenne d'elle même (elle devrait) une fois que des données récentes seront renvoyées par l'API de RTE.

Patientons 🤷

**Comment by mathieucarbou** [comment]
Effectivement on voit bien dans la json retourné qu'il manque les données pour aujourd'hui et demain:
```json
{
   "tempo_like_calendars":{
      "start_date":"2022-10-16T00:00:00+02:00",
      "end_date":"2023-10-17T00:00:00+02:00",
      "values":[
         {
            "start_date":"2023-10-14T00:00:00+02:00",
            "end_date":"2023-10-15T00:00:00+02:00",
            "value":"BLUE",
            "updated_date":"2023-10-13T10:20:00+02:00"
         },
         {
            "start_date":"2023-10-13T00:00:00+02:00",
            "end_date":"2023-10-14T00:00:00+02:00",
            "value":"BLUE",
            "updated_date":"2023-10-12T10:20:00+02:00"
         },
```

**Comment by samourai64** [comment]
Portant ce matin ca semble bon sur le site de RTE
![image](https://github.com/hekmon/rtetempo/assets/97638377/b78c899f-fdd1-4468-b412-330e95e2db70)

**Comment by Tigafg** [comment]
Bonjour à tous,

En effet, on retrouve la couleur pour demain mais pas aujourd'hui et donc certainement un vide dans les données retournées.
Du coup pas sûr que l'intégration retrouve bien ses petits dans ce cas.

**Comment by eizo27** [comment]
Idem, j'ai la couleur de demain mais pas aujourd'hui

**Comment by luke7101** [comment]
Impeccable, merci pour les explications 👍

**Comment by inoxas78** [comment]
> Ce samedi 14 à 23h00, [le site de RTE](https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/calendrier-des-offres-de-fourniture-de-type-tempo.html) semble ne pas publier non plus la couleur pour dimanche 15: Le jour du lendemain est vide, et une info bulle laisse entendre qu'il y aurait un problème technique:
> 
> ![Capture d’écran du 2023-10-14 23-01-47](https://user-images.githubusercontent.com/24843224/275288759-b6817ca3-a7c3-47a0-94b8-c05c92099b19.png)

J'ai le meme souci mais surtout je suis tombé amoureux de ta carte home assistant......
Tu peux me dire ou la trouver stp?

**Comment by hekmon** [comment]
Il ne s'agit pas d'une carte HA mais de la [page officielle Tempo de RTE](https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/calendrier-des-offres-de-fourniture-de-type-tempo.html) @inoxas78 ;)

**Comment by inoxas78** [comment]
Ah mais quel dommage c'était juste trop beau pour etre vrai ;)

**Comment by hekmon** [comment]
J'ai effectivement la couleur du lendemain qui s'affiche correctement dorénavant mais pas celle d'aujourd'hui. Laissons quelques jours ouvrés à RTE voir s'ils peuvent corriger où si, comme pour le 28/12, ils publieront l'information manuellement sans jamais mettre à jour leurs systèmes auquel cas je publierai une version hotfix avec la valeur en dur dans l'intégration pour éviter un trou dans les données et un mauvais comptage des jours.

**Comment by hekmon** [comment]
> Portant ce matin ca semble bon sur le site de RTE ![image](https://user-images.githubusercontent.com/97638377/275313847-b78c899f-fdd1-4468-b412-330e95e2db70.png)

La couleur du lendemain oui, celle du jour non.

**Comment by hekmon** [comment]
L'intégration semble avoir récupérée... ce qui était récupérable.
![image](https://github.com/hekmon/rtetempo/assets/3418467/31bafb72-5209-4a33-92a5-5fa0ed2681b4)

Attendons quelques jours voir comment RTE gère ce problème de leur côté avant de faire quelque chose du côté de l'intégration comme expliqué plus haut.

**Comment by samourai64** [comment]
j'ai bien l'impression que tout est revenu a la normale. j'ai bien un bouton bleu dans le calendrier HA pour le 15 octobre
Pas vérifiée le décompte des jours mais bon....

**Comment by luke7101** [comment]
Visiblement c'est rectifié côté RTE 🙂

![Screenshot_20231017_084326_Home Assistant](https://github.com/hekmon/rtetempo/assets/58976540/3b0a7817-1d00-4a0f-bac6-ee2806698712)

**Comment by hekmon** [comment]
Excellente nouvelle !

On a bien fait d'attendre un petit peu. Je clos l'issue ;)

**Comment by plouf34** [comment]
Même problème aujourd’hui!!! RAS le bol de tout ces services Enedis, Rte qui tombent en panne tous les 3j!!!

**Comment by hekmon** [comment]
Même problème, même mitigation : attendons et voyons !

Pour être honnête jusqu'au problème de la semaine dernière je n'en avais jamais rencontré jusqu'ici.

**Comment by nonobzh29** [comment]
Ça ne serait pas un problème du au changement d'heure cette fois-ci ? (+01:00 au lieu de +02:00)

**Comment by hekmon** [comment]
Peut-être côté RTE, mais le site RTE affichait le même problème que précédemment (voir les posts plus haut).

De mon côté tout est rentré dans l'ordre depuis que RTE renvoie correctement toutes les données (si ce n'est pas encore le cas pour vous c'est certainement parce que l'extension est en sommeil : vous pouvez soit attendre demain matin, soit redémarrer votre HA pour le corriger tout de suite).

**Comment by nonobzh29** [comment]
Effectivement, je n'avais pas pensé à regarder le site RTE !
Parfait si c'est réglé :)
