### ISSUE TITLE
After Update 2023.11.0

### ISSUE THREAD

**Issue by Binifada1956** [hekmon/rtetempo#24]
After the last update (2023.11.0) Scripts and Automations has no Function. Backup to 2023.10.5 bring Funktion back.
Where is the Problem?

**Comment by hekmon** [comment]
Hello,

What do you mean by "no Function" ? Have they stopped working ? Which sensors are you using as triggers ?

PS: I always answer in the language of the question but we can do this in french ;)

**Comment by Binifada1956** [comment]
Hello and thank you for the quick response!

French unfortunately not better than English, I am German 🤷‍♂️

I use an automation and a script that switches the respective tariffs blue, white, red etc..

I think it's the device ID. This will probably be changed by the update. This behaviour has also been noted in the release discussions.

See https://community.home-assistant.io/t/2023-11-to-do-add-release-title/634647/33

Cdt RolfAm 02.11.2023 um 12:38 schrieb Edouard Hur ***@***.***>:﻿
Hello,
What do you mean by "no Function" ? Have they stopped working ? Which sensors are you using as triggers ?
PS: I always answer in the language of the question but we can do this in french ;)

**Comment by hekmon** [comment]
What is bothering me is that I do not have a single error log that would point to a specific problem and so a specific solution.

IDs have not been change by the extension so if HA has changed the way is generate its IDs, I am afraid that I can not do much to get the old ones back.

I need to dig this issue to better understand what is going on.

**Comment by hekmon** [comment]
I did the upgrade to 2023.11 but it seems that my entities did not changed IDs (or I would not have history for them) :
<img width="2310" alt="image" src="https://github.com/hekmon/rtetempo/assets/3418467/111821c7-29b8-4dfb-9bc8-175c7e3ebc90">

And my automatisations seems fine too :
<img width="1066" alt="image" src="https://github.com/hekmon/rtetempo/assets/3418467/9208a8ff-a3c5-4e6a-b556-8a99d27092cf">

I am gonna need more information / logs / screenshots in order to help you, from what I see on my side everything seems fine (yet).

**Comment by Binifada1956** [comment]
For the RTE integration, the client ID and the secret are returned via the API.
The ID was then also used in the automations and in the script. See attachment.

After the update, I can neither call up, view or edit the automations nor the script.Am 02.11.2023 um 14:40 schrieb Edouard Hur ***@***.***>:﻿
I did the upgrade to 2023.11 but it seems that my entities did not changed IDs (or I would not have history for them) :

And my automatisations seems fine too :

I am gonna need more information / logs / screenshots in order to help you, from what I see on my side everything seems fine (yet).

**Comment by hekmon** [comment]
Unfortunately the attachment did not make it thru github with reply by email function. Please upload it directly within the github interface.

**Comment by Binifada1956** [comment]
👍 did it

> Am 02.11.2023 um 15:17 schrieb Rolf Hoefel ***@***.***>:
> 
> For the RTE integration, the client ID and the secret are returned via the API.
> The ID was then also used in the automations and in the script. See attachment.
> 
> After the update, I can neither call up, view or edit the automations nor the script.

**Comment by Binifada1956** [comment]
any Idea?

**Comment by hekmon** [comment]
This is weird :
* The ID you have in your first screenshot is the application ID you created from RTE tu use the API
* The device_id of the Home Assistant device is something entirely different, internal of HA

Both you not match in any way.

For example, if I setup an automation with the same trigger as yours:
![image](https://github.com/hekmon/rtetempo/assets/3418467/ba512599-783d-40b0-b24c-23c269d3fe64)
This translates to the following YAML:
![image](https://github.com/hekmon/rtetempo/assets/3418467/54ad1275-5095-468c-8b94-0c4b4f0e4836)

Which no way near my RTE API Application ID:
![image](https://github.com/hekmon/rtetempo/assets/3418467/46ab2d1d-b633-4572-a72c-72a097f4e926)

So I am not sure how you ended up in this situation but I would recommend to edit your automation and recreate the trigger with the UI to get the correct HA device_id.

**Comment by Binifada1956** [comment]
ok, I'll adjust my automation and the script.
I'll know more the next time I switch between HP and HC.
Many thanksCdt RolfAm 04.11.2023 um 09:38 schrieb Edouard Hur ***@***.***>:﻿
This is weird :

The ID you have in your first screenshot is the application ID you created from RTE tu use the API
The device_id of the Home Assistant device is something entirely different, internal of HA

Both you not match in any way.
For example, if I setup an automation with the same trigger as yours:

This translates to the following YAML:

Which no way near my RTE API Application ID:

So I am not sure how you ended up in this situation but I would recommend to edit your automation and recreate the trigger with the UI to get the correct HA device_id.

**Comment by Binifada1956** [comment]
Good morning,

Everything works, even after the 2023.11.x update.
Without your help I would certainly not have solved the problem so quickly. Many thanks for that.

Greetings
Rolf alias Binifada

**Comment by hekmon** [comment]
Thanks for letting me know that everything is in order 👍
