### ISSUE TITLE
Colours in calendar

### ISSUE THREAD

**Issue by RonnieCollo** [hekmon/rtetempo#26]
Bonjour, merci pour ce merveilleux addition pour mon HA. Ca marche très bien, sauf les couleurs dans le calendrier (mois) car tous les jours sont bleu si je choisi le mois. Pour le jour et la semaine c'est correct.

**Comment by RonnieCollo** [comment]
Juste trouvé la solution dans un ancien "issue"

**Comment by RonnieCollo** [comment]
Juste trouvé la solution dans un ancien "issue"

**Comment by HermesHonshappo** [comment]
Pour ceux tombant ici par hasard comme moi, l'issue closed en question est là: https://github.com/hekmon/rtetempo/issues/9
(La solution est une carte spéciale disponible via HACS)
