### ISSUE TITLE
Possibilité d'utiliser une API ouverte pour simplifier l'installation ?

### ISSUE THREAD

**Issue by jarthod** [hekmon/rtetempo#27]
Bonjour et merci pour cet intégration que vais surement utiliser ☺

En voyant la necessité d'utiliser l'API RTE et de créer un compte pour chaque utilisateur par contre je me suis dit que c'était vraiment dommage pour une API aussi simple d'avoir autant de friction. J'ai cherché sur internet et trouvé https://www.api-couleur-tempo.fr/ qui permet de retirer cette friction en fournissant un simple proxy ouvert + un peu de caching pour la rendre plus fiable.

Je me demandais donc si ce serait possible (et facile) de modifier `rtetempo` pour utiliser cette API a la place et donc simplifier l'installation pour tout le monde ? (et le code probablement) Si c'est le cas je veux bien passer du temps dessus pour essayer de proposer une PR mais comme je ne suis pas familier avec Python ou avec HA je ne préfère pas perdre du temps là dedans si ça vous parait trop compliqué ou non désirable pour d'autres raisons.

**Comment by hekmon** [comment]
Bonjour @jarthod ,

Malheureusement je souhaite garder la SoT (source of truth) au plus proche de l'origine : c'est pour cela que j'ai préféré utiliser l'API de RTE et non celle d'EDF par exemple au début du projet.

Donc pour pour rtetempo, non, je ne souhaite pas reposer sur un tiers mais bien me fournir à la source.

Cependant n'hésitez pas à forker le projet cette approche intéressera certainement d'autres utilisateurs !

**Comment by jarthod** [comment]
Ok ça marche :+1:
