### ISSUE TITLE
EDF Zen Flex jour sobriété

### ISSUE THREAD

**Issue by Gandulf78** [hekmon/rtetempo#28]
Bonjour. 
Est-ce qu'il serait possible d'adapter l'intégration pour qu'elle récupère l'information des "jours sobriété" EDF? (Publiés par EDF du jour pour le lendemain pour les jours Rouges Tempo). 
Merci.

**Comment by hekmon** [comment]
Bonjour,

Cette intégration étant spécifiquement développée pour Tempo, ce n'est pas quelque chose que je souhaite rajouter. En plus de sortir du scope, rajouter un tel support impliquerait de rajouter un tout nouveau contrôleur d'API : en effet je n'utilise pas d'API EDF pour récupérer les jours tempos mais une API de RTE (c'est ce qui permet d'avoir l'information bien plus rapidement qu'avec n'importe qu'elle autre méthode). RTE décide des jours tempo pour les fournisseurs d'électricité qui les republient à leur tour par rapport à leurs forfaits liés à Tempo, s'ils en ont.

Les jours de sobriétés EDF de l'offre zen flex étant un forfait purement EDF par rapport au marché ces derniers pourraient tout à fait ne plus suivre les jours rouges tempo à l'avenir (ils devraient rester très proches cependant).

Donc bien qu'étant proche, ces jours ne sont pas exactement la même chose et hors du scope de cette intégration :)
