### ISSUE TITLE
Sensors de prix pour le dashboard energy

### ISSUE THREAD

**Issue by Toukite** [hekmon/rtetempo#29]
Bonjour,

Merci pour cette intégration très utile !

Je me demandais si cette intégration saurait récupérer les tarifs ttc "officiels" via une api, et les exposer comme sensor ?
Un peu comme ceci (sensors créés et maintenus à la main):
![Screenshot_2024-01-23-23-02-38-38_c3a231c25ed346e59462e84656a70e50](https://github.com/hekmon/rtetempo/assets/42780622/98a61873-4e8f-4593-86f3-a6b88765c486)

L'idée serait de pouvoir associer ces sensors de tarifs aux sources correspondantes dans le dashboard energy, comme ça pas besoin de penser à les changer à la main le jour J à chaque augmentation !

Mais je ne sais pas si ces tarifs sont exposés par une api... Qu'en pensez vous ?

**Comment by hekmon** [comment]
Cela dépasserait le scope de cette intégration malheureusement :)

Plus de détails [ici](https://github.com/hekmon/rtetempo/issues/8#issuecomment-1435783025) et [ici](https://github.com/hekmon/rtetempo/issues/28#issuecomment-1914206676) sur le scope RTE vs EDF.

J'ai bien entendu réfléchis moi même a faire une intégration spécifique aux prix EDF afin de pouvoir marier les sensors des 2 directement dans le dashboard énergie, cependant :

- Aucune API officielle d'EDF ne donne l'information
- Donc une intégration proposant ces informations se baseraient forcément sur une donnée entrée "à la main" depuis un serveur
- Le développeur de cette intégration aurait donc la responsabilité de rajouter ces informations "au plus vite" dès la publication des nouveaux tarifs car pour ses utilisateurs, un sensor automatique doit se mettre à jour tout seul mais surtout au bon moment !
- Ce n'est pas un responsabilité que je suis prêt à prendre à la vue de ma vie pro et perso bien chargée et du peu de temps libre disponible qui en découle

Donc pour le moment (et tant qu'il n'y aura pas d'API d'EDF propre pour y répondre), je préfère que la responsabilité de mettre à jour les tarifs au bon moment soit au niveau de l'utilisateur. Cela ne veut pas dire que je ne peux pas aiguiller sur comment le faire au plus propre et au plus facile (voir `Affichage dynamiques des prix` dans la [dernière section du readme](https://github.com/hekmon/rtetempo?tab=readme-ov-file#exemples-de-cartes-lovelace) avec les `input numbers` et les `templates`) mais que je ne souhaite pas créer quelque chose qui ne serait pas 100% autonome et dynamique.

**Comment by NicoIIT** [comment]
Bonjour,

Je me permet de relancer ce topic avec les informations que j'ai trouvé sur des données officielles (data.gouv.fr):
https://www.data.gouv.fr/datasets/historique-des-tarifs-reglementes-de-vente-delectricite-pour-les-consommateurs-residentiels/

Il existe une API REST JSON pour acceder à ces data (avec doc sur le filtrage, ...):
https://www.data.gouv.fr/dataservices/api-tabulaire-data-gouv-fr-beta/

En particulier pour l'historique des prix Tempo (rid: `0c3d1d36-c412-4620-8566-e5cbb4fa2b5a`), incluant les derniers / futurs prix (mise à jour le 4 juillet 2025 pour les tarifs entrant en vigueur le 1er Aout 2025):
https://tabular-api.data.gouv.fr/api/resources/0c3d1d36-c412-4620-8566-e5cbb4fa2b5a/data/

Il est possible de filtrer pour trouver les infos plus interessantes, par exemple l'historique pour une puissance souscrite 9A (seul l'abonnement/PART_FIXE change pour une puissance souscrite différente) en ordre descendant:
https://tabular-api.data.gouv.fr/api/resources/0c3d1d36-c412-4620-8566-e5cbb4fa2b5a/data/?DATE_DEBUT__sort=desc&P_SOUSCRITE__exact=9

ou encore pour les tarifs à partir de Août 2025:
https://tabular-api.data.gouv.fr/api/resources/0c3d1d36-c412-4620-8566-e5cbb4fa2b5a/data/?DATE_DEBUT__exact=2025-01-08&P_SOUSCRITE__exact=9

A noter que la date de début de chaque période soit au format YYYY-DD-MM (ce qui empêche une comparaison avec la date du jour directement...) , et la date de fin YYYY-MM-DD... 

Je conviens que cela sort du scope de cette intégration, toutefois Je pense qu'avec cette API il devrait être possible d'avoir des prix dynamiques sans maintenance 😃 (potentiellement dans une autre integration)
