### ISSUE TITLE
Accès à sensor.edf_tempo_prix_actuel pour calculer le prix de la consommation

### ISSUE THREAD

**Issue by pihomeserver** [hekmon/rtetempo#30]
Bonjour
J'ai une installation HA dans docker où j'ai installé RTE TEmpo (encore bravo pour le travail !) et un autre container qui récupère la consommation Linky

Dans le tableau d'énergie j'ai pu ajouter la source Linky et il me propose de calculer le cout et pour cela il lui faut un capteur qui va suivre le cout. J'aurais voulu utiliser sensor.edf_tempo_prix_actuel qui fonctionne très bien mais je ne le vois pas dans la liste
La doc demande de configurer "correctement" ce capteur mais je n'ai aucune idée de ce que ca signifie

Si vous avez une idée de comment le rendre accessible je suis preneur 
Merci

**Comment by croftman** [comment]
Salut !
Il te faut juste ajouter les input_numbers https://gist.github.com/hekmon/33cba41728bfe2e4e522851da052f91f et ensuite le template : https://gist.github.com/hekmon/c2f64f22f58b92eae007797eb1a2732e

Tu retrouveras ensuite les sensors HP/HC Rouge Bleu Blanc et le tarif tempo du jour et du lendemain !

**Comment by pihomeserver** [comment]
@croftman Merci pour ton retour. Je me suis mal exprimé. J'ai bien suivi la documentation et tout est ok j'ai bien un tableau qui affiche toutes les infos y compris le prix en cours dans sensor.edf_tempo_prix_actuel

![image](https://github.com/hekmon/rtetempo/assets/3817578/ceeaea42-e34f-462a-a86f-96d19e092f77)


Mon point est dans le tableau "Energie" par défaut où j'ai ajouté ma conso link et je voudrais que le prix soit calculé en temps réel. Or je ne peux pas choisir le capteur car l'option est grisée

![image](https://github.com/hekmon/rtetempo/assets/3817578/c5c2a624-cb4a-4844-ae9e-0b540abee661)

Je ne sais pas si c'est la configuration de Linky, Home Assistant ou RTE

**Comment by croftman** [comment]
Ok je vois, et bien c'est activé chez moi, j'ai un teleinfokit, peut être que ton "Linky Consumption" bloque le calcul

**Comment by pihomeserver** [comment]
@croftman en creusant un peu plus le problème vient que les sources Linky viennent d'en dehors de HA. Elles sont considérées comme statistiques externes et dans ce cas HA ne permet pas d'y ajouter un calcul. J'avais zappé la discussion [ici](https://github.com/bokub/ha-linky/issues/2#issuecomment-1705521229)

**Comment by croftman** [comment]
@pihomeserver ok je comprends mieux ! Tu as donc le teleinfokit (mais pas sur qu'il soit encore vendu) ou des modules à brancher en direct sur le linky en zigbee autoalimenté si jamais tu veux pouvoir gérer tes couts
Sinon regarde du côté de https://myelectricaldata.fr

**Comment by pihomeserver** [comment]
Merci ! Je vais regarder pour voir ce qui pourrait fonctionner pour mon installation car Home Assistant est installé avec docker sur un VPS donc il va surement me falloir une passerelle en "local"

**Comment by croftman** [comment]
Ah oui c'est particulier, en effet soit passer direct par myelectricaldata, ou bien avoir quelque-chose qui envoi les données au VPS, mais bon la autant avoir HA à la maison

**Comment by hekmon** [comment]
Bonjour,

Il est normal que vous ne puissiez pas utiliser `sensor.edf_tempo_prix_actuel` en l'état actuel : ce sensor étant fait pour un affichage dashboard j'ai opté pour pour une unité en [centimes d'euros](https://gist.github.com/hekmon/c2f64f22f58b92eae007797eb1a2732e#file-templates-yaml-L6) afin de ne pas perdre les 3 et 4eme chiffre après la virgule lors de l'affichage sous HA.

Il est vrai que cela peut poser problème pour le dashboard énergie mais comme je l'ai expliqué dans #8 en mode Tempo je déconseille d'appliquer dynamiquement un prix sur une seule et unique mesure de la consommation (c'est au mieux une approximation) : la bonne approche est de récupérer les 6 compteurs tempo directement depuis le Linky et d'y appliquer des prix fixes.

Maintenant je crois comprendre que vous récupérez votre consommation non pas depuis votre Linky (que ce soit en zigbee ou directement en serial/tic comme avec mon autre intégration [LinkyTIC](https://github.com/hekmon/linkytic)) mais depuis votre compte Enedis directement avec [ha-linky](https://github.com/bokub/ha-linky), effectivement dans ce cas difficile de faire autrement. Outre le fait que je déconseille cette approche, pour que le sensor `sensor.edf_tempo_prix_actuel` soit théoriquement compatible avec le dashboard énergie voilà ce qu'il faudrait faire sur le template sensor :

- Passer de `c€/kWh` [ici](https://gist.github.com/hekmon/c2f64f22f58b92eae007797eb1a2732e#file-templates-yaml-L6) en `€ /kWh` (comme [ici](https://gist.github.com/hekmon/33cba41728bfe2e4e522851da052f91f#file-input_numbers-yaml-L9))
- Retirer donc la multiplication `* 100` sur chaque ligne ou elle est présente (comme [ici](https://gist.github.com/hekmon/c2f64f22f58b92eae007797eb1a2732e#file-templates-yaml-L28))

Cela devrait théoriquement rendre le sensor compatible avec le dashboard énergie. Maintenant une dernière chose me chiffonne : si l'option est grisée c'est qu'aucune entité connue de Home Assistant n'est compatible. Mais si vous avez déjà les inputs number pour le sensor template... vous devriez en avoir 9 (1 tarif base, 2 tarif HC, 6 tarifs tempo). Je ne m'explique pas pourquoi celle-ci est donc grisée.

Tentez la modification du template sensor, on ne sait jamais !

**Comment by pihomeserver** [comment]
@hekmon le sensor linky consumption n'est pas visible dans l'onglet des états. Je soupconne que cela  vienne de ma configuration. 
HA est sur un VPS dans un docker. Donc pas de add-ons. Donc j'ai installé ha-linky aussi dans un container avec un mqtt qui va faire le pont entre les deux.
L'option reste grisée car la source linky consumption est considérée comme "externe" ce que HA du coup bloque.
Reste à sortir un vieux laptop avec 4Go de RAM pour installer HA dessus et le laisser tourner à la maison. Docker semble avoir trouvé ses limites pour cet usage

**Comment by hekmon** [comment]
Je me permets de fermer l'issue puisque le problème semble venir de la source de données.

Cependant, pour la postérité j'insiste sur le fait qu'utiliser le template de prix en exemple n'est pas fait pour le dashboard énergie mais pour des dashboards avec widget. Plus d'infos [ici](https://github.com/hekmon/rtetempo/issues/30#issuecomment-1948705469) donc.
