### ISSUE TITLE
No Colourupdate

### ISSUE THREAD

**Issue by Binifada1956** [hekmon/rtetempo#31]
Hello, I updated to HA 2024.2.2 yesterday. No change of EDF colour today? See attachment.

![image](https://github.com/hekmon/rtetempo/assets/99736262/f4a80953-ac67-43ff-8507-4b5b03c26b4a)

**Comment by jloisel** [comment]
RTE EcoMix Api was down today.

**Comment by Binifada1956** [comment]
ya, seems to be working again. Thanks for the info 😎

**Comment by hekmon** [comment]
When in doubt, always check upstream first (first link of the readme) :
https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/calendrier-des-offres-de-fourniture-de-type-tempo.html

If next day color is in "degraded mode", there is nothing you or I can do but wait for RTE to fix the issue upstream :)
