### ISSUE TITLE
RTETempo et Solarman 

### ISSUE THREAD

**Issue by wixaw** [hekmon/rtetempo#41]
Bonjour 
J'utilise le plugin [https://github.com/davidrapan/ha-solarman/](url) qui override mon dashboard energy, car c'est mon onduleur qui me donne mes infos de conso
Avez vous une idée comment je pourrais intégrer la partie rtetempo dans mon Total Energy Import  ? 

![image](https://github.com/user-attachments/assets/f086d378-d72a-4ffa-a273-3ab2eeec5ad0)

Merci

**Comment by hekmon** [comment]
Malheureusement non, il y a ici 2 notions différentes :
* Le relevé de conso qui est chez vous uniforme (un seul compteur et non séparé en différents compteurs tempo comme https://github.com/hekmon/linkytic peut le faire par exemple)
* Les infos tempo actuelles de la part de RTE non lié à une consommation particulière (cette extension)

Il y a déjà eu des tentatives (que j'ai linké dans cette [conversation](https://github.com/hekmon/rtetempo/issues/8#issuecomment-1435783025) d'associer dynamiquement les 2 dans HA mais ce n'est pas une approche que je recommande.

**Comment by wixaw** [comment]
Merci pour le retour tant pis :)
