### ISSUE TITLE
Récupération des tarifs

### ISSUE THREAD

**Issue by Feneck91** [hekmon/rtetempo#45]
Bonjour.

Je te remercie pour le travail que tu as fourni pour cette intégration qui fonctionne parfaitement bien.
J'ai réalisé une carte basée sur ton intégration : https://forum.hacf.fr/t/rte-tempo-carte/51570

Seulement voilà, ton intégration ne donne pas les tarifs. Au lieu de cela, j'utilise l'intégration Tarif EDF.
J'ai tenté de mettre à jour les 6 tarifs bleu / blanc / rouge et HP et HC avec le changement HP / HC automatiquement. Hélas, la mise à jour du tarif courant arrive n'importe quand et je n'arrive pas à le mettre en corrélation avec la couleur du jour, du coup ça se met à jour n'importe comment. Tu me diras que ce n'est pas ton intégration et cela est vrai.

Je m'apprête à faire ma propre intégration pour récupérer tous les tarifs d'un coup + l'abonnement en fonction du nombre de KVA.
J'ai tenté de me connecter sur mon compte EDF mais impossible, le site est protégé contre les robots, impossible de se connecter facilement.

Du coup il reste ça : https://particulier.edf.fr/content/dam/2-Actifs/Documents/Offres/Grille_prix_Tarif_Bleu.pdf
Je pense qu'il est possible d'en extraire les tarifs en pythons en convertissant le pdf en texte et en recherchant les tarifs via des regex ou autre.

Tu en penses quoi ? Souhaites-tu le réaliser et l'intégrer dans ton intégration ou je fais le taf de mon côté, quitte à, par la suite, réaliser la récupération des données EDF via l'API comme tu l'as réalisé.

Cordialement.

**Comment by Bambouzle** [comment]
Salut,

Pour la récupération des tarifs ce serait sûrement possible en utilisant les id des span dans le HTML mais ça a de fortes chances de casser au prochain changement de prix. Je vais essayer de creuser cette piste.

Pour la gestion du prix de l'électricité j'ai fait 7 input number (cf. photo) et une automatisation qui se trigger à l'entrée/sortie des heures creuses et au redémarrage de HA (notamment pour la reprise sur panne). Voici mon intégration :

> alias: "[BACKBONE] Gestion du tarif"
> description: ""
> triggers:
>   - entity_id:
>       - binary_sensor.rte_tempo_heures_creuses
>     to: "on"
>     trigger: state
>   - entity_id:
>       - binary_sensor.rte_tempo_heures_creuses
>     to: "off"
>     trigger: state
>   - event: start
>     trigger: homeassistant
> conditions: []
> actions:
>   - if:
>       - condition: state
>         entity_id: binary_sensor.rte_tempo_heures_creuses
>         state: "on"
>     then:
>       - alias: Tarif HC
>         choose:
>           - conditions:
>               - condition: state
>                 entity_id: sensor.rte_tempo_couleur_actuelle
>                 state: Bleu
>             sequence:
>               - data:
>                   value: "{{ states('input_number.cout_bleu_hc') }}"
>                 target:
>                   entity_id: input_number.cout_actuel
>                 action: input_number.set_value
>           - conditions:
>               - condition: state
>                 entity_id: sensor.rte_tempo_couleur_actuelle
>                 state: Blanc
>             sequence:
>               - data:
>                   value: "{{ states('input_number.cout_blanc_hc') }}"
>                 target:
>                   entity_id: input_number.cout_actuel
>                 action: input_number.set_value
>           - conditions:
>               - condition: state
>                 entity_id: sensor.rte_tempo_couleur_actuelle
>                 state: Rouge
>             sequence:
>               - data:
>                   value: "{{ states('input_number.cout_rouge_hc') }}"
>                 target:
>                   entity_id: input_number.cout_actuel
>                 action: input_number.set_value
>         default:
>           - data:
>               value: "{{ states('input_number.cout_bleu_hc') }}"
>             target:
>               entity_id: input_number.cout_actuel
>             action: input_number.set_value
>             alias: Tarif HC Bleu
>     else:
>       - alias: Tarif HP
>         choose:
>           - conditions:
>               - condition: state
>                 entity_id: sensor.rte_tempo_couleur_actuelle
>                 state: Bleu
>             sequence:
>               - data:
>                   value: "{{ states('input_number.cout_bleu_hp') }}"
>                 target:
>                   entity_id: input_number.cout_actuel
>                 action: input_number.set_value
>           - conditions:
>               - condition: state
>                 entity_id: sensor.rte_tempo_couleur_actuelle
>                 state: Blanc
>             sequence:
>               - data:
>                   value: "{{ states('input_number.cout_blanc_hp') }}"
>                 target:
>                   entity_id: input_number.cout_actuel
>                 action: input_number.set_value
>           - conditions:
>               - condition: state
>                 entity_id: sensor.rte_tempo_couleur_actuelle
>                 state: Rouge
>             sequence:
>               - data:
>                   value: "{{ states('input_number.cout_rouge_hp') }}"
>                 target:
>                   entity_id: input_number.cout_actuel
>                 action: input_number.set_value
>         default:
>           - data:
>               value: "{{ states('input_number.cout_bleu_hp') }}"
>             target:
>               entity_id: input_number.cout_actuel
>             action: input_number.set_value
>             alias: Tarif HP Bleu
> mode: single


Les 7 input number:
![image](https://github.com/user-attachments/assets/dd5f83cd-ac32-423c-ba13-077e0b827a40)

Bonne soirée

**Comment by Feneck91** [comment]
Oui mais tu mets le coût actuel à jour mais les tarifs sont claqués en dur et pas récurpérés.

Ce que je pensais faire, c'est https://www.geeksforgeeks.org/extract-text-from-pdf-file-using-python/
En gros récupérer le texte du pdf, en plus tu peux mettre dans un champ la date a laquelle la grille de tarif s'applique.
Avec des regex, ça doit être facile à parser.

Par contre, franchement, utilise le € au lieu de EUR, c'est bien plus beau ;-)

**Comment by hekmon** [comment]
C'est un sujet qui revient souvent. J'ai voulu me pencherdessus mais au final j'ai préféré abandonné (et rester sur une update manuelle de mes constantes indiquées dans le readme).

Plus d'information ici : https://github.com/hekmon/rtetempo/issues/29#issuecomment-1914219406
